### ISSUE TITLE
termux bugs

### ISSUE THREAD

**Issue by passerbyo** [codingcn/go-web-demo#2]
unexpected fault address 0x808085a175a75
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x808085a175a75 pc=0x5e1014d4f0]

goroutine 40 [running]:
runtime.throw({0x5e0ffe5e8c?, 0x718af957a0?})
        /data/data/com.termux/files/usr/lib/go/src/runtime/panic.go:992 +0x50 fp=0x40000c3210 sp=0x40000c31e0 pc=0x5e1011fac0
runtime.sigpanic()
        /data/data/com.termux/files/usr/lib/go/src/runtime/signal_unix.go:825 +0x1a4 fp=0x40000c3240 sp=0x40000c3210 pc=0x5e10135de4
aeshashbody()
        /data/data/com.termux/files/usr/lib/go/src/runtime/asm_arm64.s:878 +0x2d0 fp=0x40000c3250 sp=0x40000c3250 pc=0x5e1014d4f0
runtime.mapiternext(0x4000437b40)
        /data/data/com.termux/files/usr/lib/go/src/runtime/map.go:934 +0x2c4 fp=0x40000c32c0 sp=0x40000c3250 pc=0x5e100fa7d4
runtime.mapiterinit(0x5e10ac8a00?, 0x4000297380?, 0x0?)
        /data/data/com.termux/files/usr/lib/go/src/runtime/map.go:861 +0x2f0 fp=0x40000c32f0 sp=0x40000c32c0 pc=0x5e100fa4d0
reflect.mapiterinit(0x40000c33e8?, 0x5e100f7dd0?, 0x40000c3418?)
        /data/data/com.termux/files/usr/lib/go/src/runtime/map.go:1373 +0x20 fp=0x40000c3320 sp=0x40000c32f0 pc=0x5e10149bb0
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:112
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0x4000429110, 0x4000291038, 0x4000280a80)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect_map.go:291 +0x244 fp=0x40000c3490 sp=0x40000c3320 pc=0x5e105316a4
github.com/json-iterator/go.(*onePtrEncoder).Encode(0x400040dda0, 0x4000428ba0, 0x4000437b40?)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect.go:219 +0x8c fp=0x40000c34d0 sp=0x40000c3490 pc=0x5e1052a16c
github.com/json-iterator/go.(*Stream).WriteVal(0x4000280a80, {0x5e106f3200, 0x4000428ba0})
        /data/data/com.termux/files/home/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect.go:98 +0x174 fp=0x40000c3550 sp=0x40000c34d0 pc=0x5e10529534
github.com/json-iterator/go.(*frozenConfig).Marshal(0x40002b03c0, {0x5e106f3200, 0x4000428ba0})
        /data/data/com.termux/files/home/go/pkg/mod/github.com/json-iterator/go@v1.1.8/config.go:299 +0x88 fp=0x40000c35f0 sp=0x40000c3550 pc=0x5e10520a68
go-web-demo/app/middlewares.CommonMiddleware.func1(0x40002972b0)
        /data/data/com.termux/files/home/go-web-demo/app/middlewares/common.go:23 +0x228 fp=0x40000c37e0 sp=0x40000c35f0 pc=0x5e1059c768
github.com/gin-gonic/gin.(*Context).Next(...)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147
go-web-demo/app/middlewares.Metric.func1(0x40002972b0)
        /data/data/com.termux/files/home/go-web-demo/app/middlewares/prometheus.go:70 +0x2a8 fp=0x40000c3860 sp=0x40000c37e0 pc=0x5e1059e568
github.com/gin-gonic/gin.(*Context).Next(...)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0x4000425180, 0x40002972b0)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:403 +0x528 fp=0x40000c3a40 sp=0x40000c3860 pc=0x5e104e9088
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0x4000425180, {0x5e107294b0?, 0x40002d4380}, 0x4000439100)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:364 +0x1c4 fp=0x40000c3a80 sp=0x40000c3a40 pc=0x5e104e89c4
net/http.serverHandler.ServeHTTP({0x4000428b10?}, {0x5e107294b0, 0x40002d4380}, 0x4000439100)
        /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:2916 +0x40c fp=0x40000c3b40 sp=0x40000c3a80 pc=0x5e1034da4c
net/http.(*conn).serve(0x40004239a0, {0x5e10729ca8, 0x40001cb590})
        /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:1966 +0x56c fp=0x40000c3fa0 sp=0x40000c3b40 pc=0x5e1034913c
net/http.(*Server).Serve.func3()
        /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:3071 +0x34 fp=0x40000c3fd0 sp=0x40000c3fa0 pc=0x5e1034e294
runtime.goexit()
        /data/data/com.termux/files/usr/lib/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x40000c3fd0 sp=0x40000c3fd0 pc=0x5e10150534
created by net/http.(*Server).Serve
        /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:3071 +0x450

goroutine 1 [chan receive]:
main.Graceful()
        /data/data/com.termux/files/home/go-web-demo/main.go:124 +0x454
main.main()
        /data/data/com.termux/files/home/go-web-demo/main.go:44 +0xbc

goroutine 25 [syscall]:
os/signal.signal_recv()
        /data/data/com.termux/files/usr/lib/go/src/runtime/sigqueue.go:151 +0x34
os/signal.loop()
        /data/data/com.termux/files/usr/lib/go/src/os/signal/signal_unix.go:23 +0x20
created by os/signal.Notify.func1.1
        /data/data/com.termux/files/usr/lib/go/src/os/signal/signal.go:151 +0x30

goroutine 36 [select]:
github.com/cloudflare/tableflip.(*Upgrader).run(0x400043a680)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/cloudflare/tableflip@v1.0.0/upgrader.go:200 +0xd8
created by github.com/cloudflare/tableflip.newUpgrader
        /data/data/com.termux/files/home/go/pkg/mod/github.com/cloudflare/tableflip@v1.0.0/upgrader.go:95 +0x304

goroutine 37 [chan receive]:
main.Graceful.func1()
        /data/data/com.termux/files/home/go-web-demo/main.go:81 +0xd0
created by main.Graceful
        /data/data/com.termux/files/home/go-web-demo/main.go:78 +0x12c

goroutine 24 [select]:
github.com/robfig/cron.(*Cron).run(0x400009efa0)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:191 +0x464
created by github.com/robfig/cron.(*Cron).Start
        /data/data/com.termux/files/home/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:144 +0x74

goroutine 38 [IO wait]:
internal/poll.runtime_pollWait(0x718af91fb0, 0x72)
        /data/data/com.termux/files/usr/lib/go/src/runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0x400043a780?, 0x5e10164904?, 0x0)
        /data/data/com.termux/files/usr/lib/go/src/internal/poll/fd_poll_runtime.go:83 +0x2c
internal/poll.(*pollDesc).waitRead(...)
        /data/data/com.termux/files/usr/lib/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0x400043a780)
        /data/data/com.termux/files/usr/lib/go/src/internal/poll/fd_unix.go:614 +0x1d0
net.(*netFD).accept(0x400043a780)
        /data/data/com.termux/files/usr/lib/go/src/net/fd_unix.go:172 +0x28
net.(*TCPListener).accept(0x400028d710)
        /data/data/com.termux/files/usr/lib/go/src/net/tcpsock_posix.go:139 +0x2c
net.(*TCPListener).Accept(0x400028d710)
        /data/data/com.termux/files/usr/lib/go/src/net/tcpsock.go:288 +0x30
net/http.(*Server).Serve(0x40002d42a0, {0x5e107292d0, 0x400028d710})
        /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:3039 +0x318
main.Graceful.func2()
        /data/data/com.termux/files/home/go-web-demo/main.go:110 +0x2c
created by main.Graceful
        /data/data/com.termux/files/home/go-web-demo/main.go:109 +0x26c

goroutine 39 [chan receive]:
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0x4000280480)
        /data/data/com.termux/files/home/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:379 +0x48
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
        /data/data/com.termux/files/home/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:390 +0xa8

goroutine 41 [IO wait]:
internal/poll.runtime_pollWait(0x718af91dd0, 0x72)
        /data/data/com.termux/files/usr/lib/go/src/runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0x400043a900?, 0x4000428b21?, 0x0)
        /data/data/com.termux/files/usr/lib/go/src/internal/poll/fd_poll_runtime.go:83 +0x2c
internal/poll.(*pollDesc).waitRead(...)
        /data/data/com.termux/files/usr/lib/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0x400043a900, {0x4000428b21, 0x1, 0x1})
        /data/data/com.termux/files/usr/lib/go/src/internal/poll/fd_unix.go:167 +0x1e4
net.(*netFD).Read(0x400043a900, {0x4000428b21?, 0x0?, 0x0?})
        /data/data/com.termux/files/usr/lib/go/src/net/fd_posix.go:55 +0x2c
net.(*conn).Read(0x4000290fd8, {0x4000428b21?, 0x0?, 0x0?})
        /data/data/com.termux/files/usr/lib/go/src/net/net.go:183 +0x38
net/http.(*connReader).backgroundRead(0x4000428b10)
        /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:672 +0x48
created by net/http.(*connReader).startBackgroundRead
        /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:668 +0xd0
exit status 2

**Comment by codingcn** [comment]
> unexpected fault address 0x808085a175a75 fatal error: fault [signal SIGSEGV: segmentation violation code=0x1 addr=0x808085a175a75 pc=0x5e1014d4f0]
> 
> goroutine 40 [running]: runtime.throw({0x5e0ffe5e8c?, 0x718af957a0?}) /data/data/com.termux/files/usr/lib/go/src/runtime/panic.go:992 +0x50 fp=0x40000c3210 sp=0x40000c31e0 pc=0x5e1011fac0 runtime.sigpanic() /data/data/com.termux/files/usr/lib/go/src/runtime/signal_unix.go:825 +0x1a4 fp=0x40000c3240 sp=0x40000c3210 pc=0x5e10135de4 aeshashbody() /data/data/com.termux/files/usr/lib/go/src/runtime/asm_arm64.s:878 +0x2d0 fp=0x40000c3250 sp=0x40000c3250 pc=0x5e1014d4f0 runtime.mapiternext(0x4000437b40) /data/data/com.termux/files/usr/lib/go/src/runtime/map.go:934 +0x2c4 fp=0x40000c32c0 sp=0x40000c3250 pc=0x5e100fa7d4 runtime.mapiterinit(0x5e10ac8a00?, 0x4000297380?, 0x0?) /data/data/com.termux/files/usr/lib/go/src/runtime/map.go:861 +0x2f0 fp=0x40000c32f0 sp=0x40000c32c0 pc=0x5e100fa4d0 reflect.mapiterinit(0x40000c33e8?, 0x5e100f7dd0?, 0x40000c3418?) /data/data/com.termux/files/usr/lib/go/src/runtime/map.go:1373 +0x20 fp=0x40000c3320 sp=0x40000c32f0 pc=0x5e10149bb0 github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...) /data/data/com.termux/files/home/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:112 github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0x4000429110, 0x4000291038, 0x4000280a80) /data/data/com.termux/files/home/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect_map.go:291 +0x244 fp=0x40000c3490 sp=0x40000c3320 pc=0x5e105316a4 github.com/json-iterator/go.(*onePtrEncoder).Encode(0x400040dda0, 0x4000428ba0, 0x4000437b40?) /data/data/com.termux/files/home/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect.go:219 +0x8c fp=0x40000c34d0 sp=0x40000c3490 pc=0x5e1052a16c github.com/json-iterator/go.(*Stream).WriteVal(0x4000280a80, {0x5e106f3200, 0x4000428ba0}) /data/data/com.termux/files/home/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect.go:98 +0x174 fp=0x40000c3550 sp=0x40000c34d0 pc=0x5e10529534 github.com/json-iterator/go.(*frozenConfig).Marshal(0x40002b03c0, {0x5e106f3200, 0x4000428ba0}) /data/data/com.termux/files/home/go/pkg/mod/github.com/json-iterator/go@v1.1.8/config.go:299 +0x88 fp=0x40000c35f0 sp=0x40000c3550 pc=0x5e10520a68 go-web-demo/app/middlewares.CommonMiddleware.func1(0x40002972b0) /data/data/com.termux/files/home/go-web-demo/app/middlewares/common.go:23 +0x228 fp=0x40000c37e0 sp=0x40000c35f0 pc=0x5e1059c768 github.com/gin-gonic/gin.(*Context).Next(...) /data/data/com.termux/files/home/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 go-web-demo/app/middlewares.Metric.func1(0x40002972b0) /data/data/com.termux/files/home/go-web-demo/app/middlewares/prometheus.go:70 +0x2a8 fp=0x40000c3860 sp=0x40000c37e0 pc=0x5e1059e568 github.com/gin-gonic/gin.(*Context).Next(...) /data/data/com.termux/files/home/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0x4000425180, 0x40002972b0) /data/data/com.termux/files/home/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:403 +0x528 fp=0x40000c3a40 sp=0x40000c3860 pc=0x5e104e9088 github.com/gin-gonic/gin.(*Engine).ServeHTTP(0x4000425180, {0x5e107294b0?, 0x40002d4380}, 0x4000439100) /data/data/com.termux/files/home/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:364 +0x1c4 fp=0x40000c3a80 sp=0x40000c3a40 pc=0x5e104e89c4 net/http.serverHandler.ServeHTTP({0x4000428b10?}, {0x5e107294b0, 0x40002d4380}, 0x4000439100) /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:2916 +0x40c fp=0x40000c3b40 sp=0x40000c3a80 pc=0x5e1034da4c net/http.(*conn).serve(0x40004239a0, {0x5e10729ca8, 0x40001cb590}) /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:1966 +0x56c fp=0x40000c3fa0 sp=0x40000c3b40 pc=0x5e1034913c net/http.(*Server).Serve.func3() /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:3071 +0x34 fp=0x40000c3fd0 sp=0x40000c3fa0 pc=0x5e1034e294 runtime.goexit() /data/data/com.termux/files/usr/lib/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x40000c3fd0 sp=0x40000c3fd0 pc=0x5e10150534 created by net/http.(*Server).Serve /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:3071 +0x450
> 
> goroutine 1 [chan receive]: main.Graceful() /data/data/com.termux/files/home/go-web-demo/main.go:124 +0x454 main.main() /data/data/com.termux/files/home/go-web-demo/main.go:44 +0xbc
> 
> goroutine 25 [syscall]: os/signal.signal_recv() /data/data/com.termux/files/usr/lib/go/src/runtime/sigqueue.go:151 +0x34 os/signal.loop() /data/data/com.termux/files/usr/lib/go/src/os/signal/signal_unix.go:23 +0x20 created by os/signal.Notify.func1.1 /data/data/com.termux/files/usr/lib/go/src/os/signal/signal.go:151 +0x30
> 
> goroutine 36 [select]: github.com/cloudflare/tableflip.(*Upgrader).run(0x400043a680) /data/data/com.termux/files/home/go/pkg/mod/github.com/cloudflare/tableflip@v1.0.0/upgrader.go:200 +0xd8 created by github.com/cloudflare/tableflip.newUpgrader /data/data/com.termux/files/home/go/pkg/mod/github.com/cloudflare/tableflip@v1.0.0/upgrader.go:95 +0x304
> 
> goroutine 37 [chan receive]: main.Graceful.func1() /data/data/com.termux/files/home/go-web-demo/main.go:81 +0xd0 created by main.Graceful /data/data/com.termux/files/home/go-web-demo/main.go:78 +0x12c
> 
> goroutine 24 [select]: github.com/robfig/cron.(*Cron).run(0x400009efa0) /data/data/com.termux/files/home/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:191 +0x464 created by github.com/robfig/cron.(*Cron).Start /data/data/com.termux/files/home/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:144 +0x74
> 
> goroutine 38 [IO wait]: internal/poll.runtime_pollWait(0x718af91fb0, 0x72) /data/data/com.termux/files/usr/lib/go/src/runtime/netpoll.go:302 +0xa4 internal/poll.(*pollDesc).wait(0x400043a780?, 0x5e10164904?, 0x0) /data/data/com.termux/files/usr/lib/go/src/internal/poll/fd_poll_runtime.go:83 +0x2c internal/poll.(*pollDesc).waitRead(...) /data/data/com.termux/files/usr/lib/go/src/internal/poll/fd_poll_runtime.go:88 internal/poll.(*FD).Accept(0x400043a780) /data/data/com.termux/files/usr/lib/go/src/internal/poll/fd_unix.go:614 +0x1d0 net.(*netFD).accept(0x400043a780) /data/data/com.termux/files/usr/lib/go/src/net/fd_unix.go:172 +0x28 net.(*TCPListener).accept(0x400028d710) /data/data/com.termux/files/usr/lib/go/src/net/tcpsock_posix.go:139 +0x2c net.(*TCPListener).Accept(0x400028d710) /data/data/com.termux/files/usr/lib/go/src/net/tcpsock.go:288 +0x30 net/http.(*Server).Serve(0x40002d42a0, {0x5e107292d0, 0x400028d710}) /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:3039 +0x318 main.Graceful.func2() /data/data/com.termux/files/home/go-web-demo/main.go:110 +0x2c created by main.Graceful /data/data/com.termux/files/home/go-web-demo/main.go:109 +0x26c
> 
> goroutine 39 [chan receive]: gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0x4000280480) /data/data/com.termux/files/home/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:379 +0x48 created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1 /data/data/com.termux/files/home/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:390 +0xa8
> 
> goroutine 41 [IO wait]: internal/poll.runtime_pollWait(0x718af91dd0, 0x72) /data/data/com.termux/files/usr/lib/go/src/runtime/netpoll.go:302 +0xa4 internal/poll.(*pollDesc).wait(0x400043a900?, 0x4000428b21?, 0x0) /data/data/com.termux/files/usr/lib/go/src/internal/poll/fd_poll_runtime.go:83 +0x2c internal/poll.(*pollDesc).waitRead(...) /data/data/com.termux/files/usr/lib/go/src/internal/poll/fd_poll_runtime.go:88 internal/poll.(*FD).Read(0x400043a900, {0x4000428b21, 0x1, 0x1}) /data/data/com.termux/files/usr/lib/go/src/internal/poll/fd_unix.go:167 +0x1e4 net.(*netFD).Read(0x400043a900, {0x4000428b21?, 0x0?, 0x0?}) /data/data/com.termux/files/usr/lib/go/src/net/fd_posix.go:55 +0x2c net.(*conn).Read(0x4000290fd8, {0x4000428b21?, 0x0?, 0x0?}) /data/data/com.termux/files/usr/lib/go/src/net/net.go:183 +0x38 net/http.(*connReader).backgroundRead(0x4000428b10) /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:672 +0x48 created by net/http.(*connReader).startBackgroundRead /data/data/com.termux/files/usr/lib/go/src/net/http/server.go:668 +0xd0 exit status 2

Thank you. I have upgraded the relevant dependency libraries. Please pull them again
